language: rust
cache: cargo

before_script:
  - rustup component add rustfmt-preview

matrix:
  include:
  - rust: nightly
    script:
    - cargo test
    - cargo fmt --all -- --check

notifications:
  slack:
    rooms:
      - dalek-cryptography:Xxv9WotKYWdSoKlgKNqXiHoD#dalek-bots
